### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ampersanda** [ampersanda/flutter-android-signing#2]
- [ ] Overwrite keystore config value than skipping
- [ ] Keystore path prompt is not in right order
- [ ] Find keystore in current folder
- [ ] Use Graalvm
- [ ] Unsign project
- [ ] `-apk` is not working
